=== DataDog/libdatadog/docs/RFCs/artifacts/0002-crashtracker-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "StructuredCrashInfo",
  "type": "object",
  "required": [
    "error",
    "incomplete",
    "os_info",
    "uuid",
    "version_id"
  ],
  "properties": {
    "counters": {
      "type": "object",
      "additionalProperties": {
        "type": "integer",
        "format": "int64"
      }
    },
    "error": {
      "$ref": "#/definitions/ErrorData"
    },
    "files": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "incomplete": {
      "type": "boolean"
    },
    "metadata": {
      "anyOf": [
        {
          "$ref": "#/definitions/Metadata"
        },
        {
          "type": "null"
        }
      ]
    },
    "os_info": {
      "$ref": "#/definitions/OsInfo"
    },
    "proc_info": {
      "anyOf": [
        {
          "$ref": "#/definitions/ProcessInfo"
        },
        {
          "type": "null"
        }
      ]
    },
    "span_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "timestamp": {
      "type": [
        "string",
        "null"
      ]
    },
    "trace_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "uuid": {
      "type": "string"
    },
    "version_id": {
      "type": "integer",
      "format": "uint64",
      "minimum": 0.0
    }
  },
  "definitions": {
    "ErrorData": {
      "type": "object",
      "required": [
        "is_crash",
        "kind",
        "message",
        "stack",
        "stack_type"
      ],
      "properties": {
        "is_crash": {
          "type": "boolean"
        },
        "kind": {
          "$ref": "#/definitions/ErrorKind"
        },
        "message": {
          "type": "string"
        },
        "stack": {
          "$ref": "#/definitions/StackTrace"
        },
        "stack_type": {
          "$ref": "#/definitions/StackType"
        },
        "threads": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Thread"
          }
        }
      }
    },
    "ErrorKind": {
      "type": "string",
      "enum": [
        "SigBus",
        "SigSegv",
        "Unknown"
      ]
    },
    "Metadata": {
      "type": "object",
      "required": [
        "family",
        "library_name",
        "library_version",
        "tags"
      ],
      "properties": {
        "family": {
          "type": "string"
        },
        "library_name": {
          "type": "string"
        },
        "library_version": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "NormalizedAddress": {
      "type": "object",
      "required": [
        "file_offset",
        "meta"
      ],
      "properties": {
        "file_offset": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0.0
        },
        "meta": {
          "$ref": "#/definitions/NormalizedAddressMeta"
        }
      }
    },
    "NormalizedAddressMeta": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Unknown"
          ]
        },
        {
          "type": "object",
          "required": [
            "Apk"
          ],
          "properties": {
            "Apk": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "Elf"
          ],
          "properties": {
            "Elf": {
              "type": "object",
              "required": [
                "path"
              ],
              "properties": {
                "build_id": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "items": {
                    "type": "integer",
                    "format": "uint8",
                    "minimum": 0.0
                  }
                },
                "path": {
                  "type": "string"
                }
              }
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "Unexpected"
          ],
          "properties": {
            "Unexpected": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "OsInfo": {
      "type": "object",
      "properties": {
        "architecture": {
          "type": "string"
        },
        "bitness": {
          "type": "string"
        },
        "os_type": {
          "type": "string"
        },
        "version": {
          "$ref": "#/definitions/Version"
        }
      }
    },
    "ProcessInfo": {
      "type": "object",
      "required": [
        "pid"
      ],
      "properties": {
        "pid": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        }
      }
    },
    "StackFrame": {
      "description": "All fields are hex encoded integers.",
      "type": "object",
      "properties": {
        "column": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint32",
          "minimum": 0.0
        },
        "file": {
          "type": [
            "string",
            "null"
          ]
        },
        "function": {
          "type": [
            "string",
            "null"
          ]
        },
        "ip": {
          "type": [
            "string",
            "null"
          ]
        },
        "line": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint32",
          "minimum": 0.0
        },
        "module_base_address": {
          "type": [
            "string",
            "null"
          ]
        },
        "normalized_ip": {
          "anyOf": [
            {
              "$ref": "#/definitions/NormalizedAddress"
            },
            {
              "type": "null"
            }
          ]
        },
        "sp": {
          "type": [
            "string",
            "null"
          ]
        },
        "symbol_address": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "StackTrace": {
      "type": "object",
      "required": [
        "format",
        "trace"
      ],
      "properties": {
        "format": {
          "$ref": "#/definitions/StackType"
        },
        "trace": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StackFrame"
          }
        }
      }
    },
    "StackType": {
      "type": "string",
      "enum": [
        "CrashTrackerV1"
      ]
    },
    "Thread": {
      "type": "object",
      "required": [
        "crashed",
        "name",
        "stack"
      ],
      "properties": {
        "crashed": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "stack": {
          "$ref": "#/definitions/StackTrace"
        },
        "state": {
          "description": "\"Platform-specific state of the thread when its state was captured (CPU registers dump for iOS, thread state enum for Android, etc.).\"",
          "type": "string"
        }
      }
    },
    "Version": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Unknown"
          ]
        },
        {
          "type": "object",
          "required": [
            "Semantic"
          ],
          "properties": {
            "Semantic": {
              "type": "array",
              "items": [
                {
                  "type": "integer",
                  "format": "uint64",
                  "minimum": 0.0
                },
                {
                  "type": "integer",
                  "format": "uint64",
                  "minimum": 0.0
                },
                {
                  "type": "integer",
                  "format": "uint64",
                  "minimum": 0.0
                }
              ],
              "maxItems": 3,
              "minItems": 3
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "Rolling"
          ],
          "properties": {
            "Rolling": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "Custom"
          ],
          "properties": {
            "Custom": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    }
  }
}

=== DataDog/libdatadog/docs/RFCs/artifacts/0002-crashtracker-example.json
{
  "counters": {
    "profiler_serializing": 0,
    "profiler_collecting_sample": 1,
    "profiler_inactive": 0,
    "profiler_unwinding": 0
  },
  "error": {
    "is_crash": true,
    "kind": "SigSegv",
    "message": "SIGSEGV",
    "source_type": "crashtracking",
    "stack": {
      "format": "CrashTrackerV1",
      "trace": [
        {
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.71/src/backtrace/libunwind.rs",
          "function": "backtrace::backtrace::libunwind::trace::hf8c7365e31b762e6",
          "ip": "0x100fa8790",
          "line": 105,
          "sp": "0x1024b32a0",
          "symbol_address": "0x100fa8790"
        },
        {
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.71/src/backtrace/mod.rs",
          "function": "backtrace::backtrace::trace_unsynchronized::h9ab8c8f7d10c580c",
          "ip": "0x100fa8790",
          "line": 66,
          "sp": "0x1024b32a0",
          "symbol_address": "0x100fa8790"
        },
        {
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/emitters.rs",
          "function": "datadog_crashtracker::collector::emitters::emit_backtrace_by_frames::h2caf0ab937da4314",
          "ip": "0x100fba34c",
          "line": 34,
          "sp": "0x1024b32f0",
          "symbol_address": "0x100fba34c"
        },
        {
          "column": 18,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/emitters.rs",
          "function": "datadog_crashtracker::collector::emitters::emit_crashreport::h9f8d0f19bdd7ecdb",
          "ip": "0x100fbcef4",
          "line": 127,
          "sp": "0x1024b3450",
          "symbol_address": "0x100fbcef4"
        },
        {
          "column": 23,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/crash_handler.rs",
          "function": "datadog_crashtracker::collector::crash_handler::handle_posix_signal_impl::h2ad003563330d808",
          "ip": "0x100fa0ab8",
          "line": 333,
          "sp": "0x1024b3640",
          "symbol_address": "0x100fa0ab8"
        },
        {
          "column": 13,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/crash_handler.rs",
          "function": "datadog_crashtracker::collector::crash_handler::handle_posix_sigaction::h8e228d028f9d26da",
          "ip": "0x100fa04c4",
          "line": 257,
          "sp": "0x1024b3a20",
          "symbol_address": "0x100fa04c4"
        },
        {
          "function": "__simple_esappend",
          "ip": "0x186b9b584",
          "sp": "0x1024b3b80",
          "symbol_address": "0x186b9b584"
        },
        {
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/api.rs",
          "function": "datadog_crashtracker::collector::api::test_crash::h9e5e006b52d60956",
          "ip": "0x100f9ce1c",
          "line": 191,
          "sp": "0x1024b3bb0",
          "symbol_address": "0x100f9ce1c"
        },
        {
          "column": 20,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/api.rs",
          "function": "datadog_crashtracker::collector::api::test_crash::{{closure}}::h750b3388d76a0682",
          "ip": "0x100f92164",
          "line": 135,
          "sp": "0x16f0b67a0",
          "symbol_address": "0x100f92164"
        },
        {
          "column": 5,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs",
          "function": "core::ops::function::FnOnce::call_once::hb1768cdf281be7e4",
          "ip": "0x100fa22ec",
          "line": 250,
          "sp": "0x16f0b67c0",
          "symbol_address": "0x100fa22ec"
        },
        {
          "column": 5,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs",
          "function": "core::ops::function::FnOnce::call_once::hdc78704e3375b6cc",
          "ip": "0x101097130",
          "line": 250,
          "sp": "0x16f0b67f0",
          "symbol_address": "0x101097130"
        },
        {
          "column": 18,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::__rust_begin_short_backtrace::ha00c83e9361a315d",
          "ip": "0x101097130",
          "line": 621,
          "sp": "0x16f0b67f0",
          "symbol_address": "0x101097130"
        },
        {
          "column": 60,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test_in_process::{{closure}}::h049a3922169151a8",
          "ip": "0x1010968a8",
          "line": 644,
          "sp": "0x16f0b6830",
          "symbol_address": "0x1010968a8"
        },
        {
          "column": 9,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs",
          "function": "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h59b471ae83578d9f",
          "ip": "0x1010968a8",
          "line": 272,
          "sp": "0x16f0b6830",
          "symbol_address": "0x1010968a8"
        },
        {
          "column": 40,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::do_call::hdcae0245e55fa0c0",
          "ip": "0x1010968a8",
          "line": 552,
          "sp": "0x16f0b6830",
          "symbol_address": "0x1010968a8"
        },
        {
          "column": 19,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::h9dc0119b564ac9cf",
          "ip": "0x1010968a8",
          "line": 516,
          "sp": "0x16f0b6830",
          "symbol_address": "0x1010968a8"
        },
        {
          "column": 14,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs",
          "function": "std::panic::catch_unwind::hab329ede8b56df3b",
          "ip": "0x1010968a8",
          "line": 146,
          "sp": "0x16f0b6830",
          "symbol_address": "0x1010968a8"
        },
        {
          "column": 27,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test_in_process::h42ddc94bb4665859",
          "ip": "0x1010968a8",
          "line": 644,
          "sp": "0x16f0b6830",
          "symbol_address": "0x1010968a8"
        },
        {
          "column": 43,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test::{{closure}}::h5bc06caf086790ae",
          "ip": "0x1010968a8",
          "line": 567,
          "sp": "0x16f0b6830",
          "symbol_address": "0x1010968a8"
        },
        {
          "column": 41,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test::{{closure}}::hf12704d7fb5fe7af",
          "ip": "0x101069264",
          "line": 595,
          "sp": "0x16f0b6db0",
          "symbol_address": "0x101069264"
        },
        {
          "column": 18,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs",
          "function": "std::sys_common::backtrace::__rust_begin_short_backtrace::hf83ba910f7522d55",
          "ip": "0x101069264",
          "line": 155,
          "sp": "0x16f0b6db0",
          "symbol_address": "0x101069264"
        },
        {
          "column": 17,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs",
          "function": "std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::he9daeef7c6950e9b",
          "ip": "0x10106d798",
          "line": 528,
          "sp": "0x16f0b6f20",
          "symbol_address": "0x10106d798"
        },
        {
          "column": 9,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs",
          "function": "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0202fb4f2537b363",
          "ip": "0x10106d798",
          "line": 272,
          "sp": "0x16f0b6f20",
          "symbol_address": "0x10106d798"
        },
        {
          "column": 40,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::do_call::hbfefa096cde588e7",
          "ip": "0x10106d798",
          "line": 552,
          "sp": "0x16f0b6f20",
          "symbol_address": "0x10106d798"
        },
        {
          "column": 19,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::hebf8b6694f3819d7",
          "ip": "0x10106d798",
          "line": 516,
          "sp": "0x16f0b6f20",
          "symbol_address": "0x10106d798"
        },
        {
          "column": 14,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs",
          "function": "std::panic::catch_unwind::h62e366e1b226d45f",
          "ip": "0x10106d798",
          "line": 146,
          "sp": "0x16f0b6f20",
          "symbol_address": "0x10106d798"
        },
        {
          "column": 30,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs",
