=== DataDog/libdatadog/docs/RFCs/artifacts/0005-crashtracker-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CrashInfo",
  "type": "object",
  "required": [
    "data_schema_version",
    "error",
    "incomplete",
    "metadata",
    "os_info",
    "proc_info",
    "sig_info",
    "timestamp",
    "uuid"
  ],
  "properties": {
    "counters": {
      "type": "object",
      "additionalProperties": {
        "type": "integer",
        "format": "int64"
      }
    },
    "data_schema_version": {
      "type": "string"
    },
    "error": {
      "$ref": "#/definitions/ErrorData"
    },
    "files": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "fingerprint": {
      "type": [
        "string",
        "null"
      ]
    },
    "incomplete": {
      "type": "boolean"
    },
    "log_messages": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "metadata": {
      "$ref": "#/definitions/Metadata"
    },
    "os_info": {
      "$ref": "#/definitions/OsInfo"
    },
    "proc_info": {
      "$ref": "#/definitions/ProcInfo"
    },
    "sig_info": {
      "$ref": "#/definitions/SigInfo"
    },
    "span_ids": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Span"
      }
    },
    "timestamp": {
      "type": "string"
    },
    "trace_ids": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Span"
      }
    },
    "uuid": {
      "type": "string"
    }
  },
  "definitions": {
    "BuildIdType": {
      "type": "string",
      "enum": [
        "GNU",
        "GO",
        "PDB",
        "PE",
        "SHA1"
      ]
    },
    "ErrorData": {
      "type": "object",
      "required": [
        "is_crash",
        "kind",
        "source_type",
        "stack"
      ],
      "properties": {
        "is_crash": {
          "type": "boolean"
        },
        "kind": {
          "$ref": "#/definitions/ErrorKind"
        },
        "message": {
          "type": [
            "string",
            "null"
          ]
        },
        "source_type": {
          "$ref": "#/definitions/SourceType"
        },
        "stack": {
          "$ref": "#/definitions/StackTrace"
        },
        "threads": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ThreadData"
          }
        }
      }
    },
    "ErrorKind": {
      "type": "string",
      "enum": [
        "Panic",
        "UnhandledException",
        "UnixSignal"
      ]
    },
    "FileType": {
      "type": "string",
      "enum": [
        "APK",
        "ELF",
        "PDB"
      ]
    },
    "Metadata": {
      "type": "object",
      "required": [
        "family",
        "library_name",
        "library_version"
      ],
      "properties": {
        "family": {
          "type": "string"
        },
        "library_name": {
          "type": "string"
        },
        "library_version": {
          "type": "string"
        },
        "tags": {
          "description": "A list of \"key:value\" tuples.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "OsInfo": {
      "type": "object",
      "required": [
        "architecture",
        "bitness",
        "os_type",
        "version"
      ],
      "properties": {
        "architecture": {
          "type": "string"
        },
        "bitness": {
          "type": "string"
        },
        "os_type": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "ProcInfo": {
      "type": "object",
      "required": [
        "pid"
      ],
      "properties": {
        "pid": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        }
      }
    },
    "SiCodes": {
      "description": "See https://man7.org/linux/man-pages/man2/sigaction.2.html",
      "type": "string",
      "enum": [
        "BUS_ADRALN",
        "BUS_ADRERR",
        "BUS_MCEERR_AO",
        "BUS_MCEERR_AR",
        "BUS_OBJERR",
        "SEGV_ACCERR",
        "SEGV_BNDERR",
        "SEGV_MAPERR",
        "SEGV_PKUERR",
        "SI_ASYNCIO",
        "SI_KERNEL",
        "SI_MESGQ",
        "SI_QUEUE",
        "SI_SIGIO",
        "SI_TIMER",
        "SI_TKILL",
        "SI_USER",
        "SYS_SECCOMP"
      ]
    },
    "SigInfo": {
      "type": "object",
      "required": [
        "si_code",
        "si_code_human_readable",
        "si_signo",
        "si_signo_human_readable"
      ],
      "properties": {
        "si_addr": {
          "type": [
            "string",
            "null"
          ]
        },
        "si_code": {
          "type": "integer",
          "format": "int32"
        },
        "si_code_human_readable": {
          "$ref": "#/definitions/SiCodes"
        },
        "si_signo": {
          "type": "integer",
          "format": "int32"
        },
        "si_signo_human_readable": {
          "$ref": "#/definitions/SignalNames"
        }
      }
    },
    "SignalNames": {
      "description": "See https://man7.org/linux/man-pages/man7/signal.7.html",
      "type": "string",
      "enum": [
        "SIGABRT",
        "SIGBUS",
        "SIGSEGV",
        "SIGSYS"
      ]
    },
    "SourceType": {
      "type": "string",
      "enum": [
        "Crashtracking"
      ]
    },
    "Span": {
      "type": "object",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "thread_name": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "StackFrame": {
      "type": "object",
      "properties": {
        "build_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "build_id_type": {
          "anyOf": [
            {
              "$ref": "#/definitions/BuildIdType"
            },
            {
              "type": "null"
            }
          ]
        },
        "column": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint32",
          "minimum": 0.0
        },
        "file": {
          "type": [
            "string",
            "null"
          ]
        },
        "file_type": {
          "anyOf": [
            {
              "$ref": "#/definitions/FileType"
            },
            {
              "type": "null"
            }
          ]
        },
        "function": {
          "type": [
            "string",
            "null"
          ]
        },
        "ip": {
          "type": [
            "string",
            "null"
          ]
        },
        "line": {
          "type": [
            "integer",
            "null"
          ],
          "format": "uint32",
          "minimum": 0.0
        },
        "module_base_address": {
          "type": [
            "string",
            "null"
          ]
        },
        "path": {
          "type": [
            "string",
            "null"
          ]
        },
        "relative_address": {
          "type": [
            "string",
            "null"
          ]
        },
        "sp": {
          "type": [
            "string",
            "null"
          ]
        },
        "symbol_address": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "StackTrace": {
      "type": "object",
      "required": [
        "format",
        "frames"
      ],
      "properties": {
        "format": {
          "type": "string"
        },
        "frames": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StackFrame"
          }
        }
      }
    },
    "ThreadData": {
      "type": "object",
      "required": [
        "crashed",
        "name",
        "stack"
      ],
      "properties": {
        "crashed": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "stack": {
          "$ref": "#/definitions/StackTrace"
        },
        "state": {
          "type": [
            "string",
            "null"
          ]
        }
      }
    }
  }
}

=== DataDog/libdatadog/docs/RFCs/artifacts/0005-crashtracker-example.json
{
  "counters": {
    "profiler_collecting_sample": 1,
    "profiler_inactive": 0,
    "profiler_unwinding": 0,
    "profiler_serializing": 0
  },
  "data_schema_version": "1.0",
  "error": {
    "is_crash": true,
    "kind": "UnixSignal",
    "source_type": "Crashtracking",
    "stack": {
      "format": "Datadog Crashtracker 1.0",
      "frames": [
        {
          "ip": "0x100cc8270",
          "sp": "0x1023370e0",
          "symbol_address": "0x100cc8270",
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/libunwind.rs",
          "function": "backtrace::backtrace::libunwind::trace::h44cd4fb81cab179c",
          "line": 116
        },
        {
          "ip": "0x100cc8270",
          "sp": "0x1023370e0",
          "symbol_address": "0x100cc8270",
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/mod.rs",
          "function": "backtrace::backtrace::trace_unsynchronized::h9864180bb5bf11b8",
          "line": 66
        },
        {
          "ip": "0x100c52a24",
          "sp": "0x102337130",
          "symbol_address": "0x100c52a24",
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/emitters.rs",
          "function": "datadog_crashtracker::collector::emitters::emit_backtrace_by_frames::hffe0893f890cf311",
          "line": 34
        },
        {
          "ip": "0x100c53f50",
          "sp": "0x102337290",
          "symbol_address": "0x100c53f50",
          "column": 18,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/emitters.rs",
          "function": "datadog_crashtracker::collector::emitters::emit_crashreport::h072d9dec8eb6d587",
          "line": 128
        },
        {
          "ip": "0x100d00120",
          "sp": "0x1023374a0",
          "symbol_address": "0x100d00120",
          "column": 15,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/crash_handler.rs",
          "function": "datadog_crashtracker::collector::crash_handler::handle_posix_signal_impl::ha45884607fab00ab",
          "line": 507
        },
        {
          "ip": "0x100cff9d0",
          "sp": "0x102337a20",
          "symbol_address": "0x100cff9d0",
          "column": 13,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/crash_handler.rs",
          "function": "datadog_crashtracker::collector::crash_handler::handle_posix_sigaction::hfda5a5ec0bcfec82",
          "line": 388
        },
        {
          "ip": "0x181022584",
          "sp": "0x102337b80",
          "symbol_address": "0x181022584",
          "function": "__simple_esappend"
        },
        {
          "ip": "0x100cdfa4c",
          "sp": "0x102337bb0",
          "symbol_address": "0x100cdfa4c",
          "column": 5,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/api.rs",
          "function": "datadog_crashtracker::collector::api::test_crash::h0310ac857cf5687f",
          "line": 157
        },
        {
          "ip": "0x100c81484",
          "sp": "0x16f3da7a0",
          "symbol_address": "0x100c81484",
          "column": 20,
          "file": "/Users/daniel.schwartznarbonne/go/src/github.com/DataDog/libdatadog/crashtracker/src/collector/api.rs",
          "function": "datadog_crashtracker::collector::api::test_crash::{{closure}}::h0b9b36ed20d8a85a",
          "line": 99
        },
        {
          "ip": "0x100ca9e80",
          "sp": "0x16f3da7c0",
          "symbol_address": "0x100ca9e80",
          "column": 5,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs",
          "function": "core::ops::function::FnOnce::call_once::h77ea56fa2b6e43e3",
          "line": 250
        },
        {
          "ip": "0x100dca6a0",
          "sp": "0x16f3da7f0",
          "symbol_address": "0x100dca6a0",
          "column": 5,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs",
          "function": "core::ops::function::FnOnce::call_once::hdc78704e3375b6cc",
          "line": 250
        },
        {
          "ip": "0x100dca6a0",
          "sp": "0x16f3da7f0",
          "symbol_address": "0x100dca6a0",
          "column": 18,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::__rust_begin_short_backtrace::ha00c83e9361a315d",
          "line": 621
        },
        {
          "ip": "0x100dc9e18",
          "sp": "0x16f3da830",
          "symbol_address": "0x100dc9e18",
          "column": 60,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test_in_process::{{closure}}::h049a3922169151a8",
          "line": 644
        },
        {
          "ip": "0x100dc9e18",
          "sp": "0x16f3da830",
          "symbol_address": "0x100dc9e18",
          "column": 9,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs",
          "function": "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h59b471ae83578d9f",
          "line": 272
        },
        {
          "ip": "0x100dc9e18",
          "sp": "0x16f3da830",
          "symbol_address": "0x100dc9e18",
          "column": 40,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::do_call::hdcae0245e55fa0c0",
          "line": 552
        },
        {
          "ip": "0x100dc9e18",
          "sp": "0x16f3da830",
          "symbol_address": "0x100dc9e18",
          "column": 19,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::h9dc0119b564ac9cf",
          "line": 516
        },
        {
          "ip": "0x100dc9e18",
          "sp": "0x16f3da830",
          "symbol_address": "0x100dc9e18",
          "column": 14,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs",
          "function": "std::panic::catch_unwind::hab329ede8b56df3b",
          "line": 146
        },
        {
          "ip": "0x100dc9e18",
          "sp": "0x16f3da830",
          "symbol_address": "0x100dc9e18",
          "column": 27,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test_in_process::h42ddc94bb4665859",
          "line": 644
        },
        {
          "ip": "0x100dc9e18",
          "sp": "0x16f3da830",
          "symbol_address": "0x100dc9e18",
          "column": 43,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test::{{closure}}::h5bc06caf086790ae",
          "line": 567
        },
        {
          "ip": "0x100d9c7d4",
          "sp": "0x16f3dadb0",
          "symbol_address": "0x100d9c7d4",
          "column": 41,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/test/src/lib.rs",
          "function": "test::run_test::{{closure}}::hf12704d7fb5fe7af",
          "line": 595
        },
        {
          "ip": "0x100d9c7d4",
          "sp": "0x16f3dadb0",
          "symbol_address": "0x100d9c7d4",
          "column": 18,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs",
          "function": "std::sys_common::backtrace::__rust_begin_short_backtrace::hf83ba910f7522d55",
          "line": 155
        },
        {
          "ip": "0x100da0d08",
          "sp": "0x16f3daf20",
          "symbol_address": "0x100da0d08",
          "column": 17,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs",
          "function": "std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::he9daeef7c6950e9b",
          "line": 528
        },
        {
          "ip": "0x100da0d08",
          "sp": "0x16f3daf20",
          "symbol_address": "0x100da0d08",
          "column": 9,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs",
          "function": "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0202fb4f2537b363",
          "line": 272
        },
        {
          "ip": "0x100da0d08",
          "sp": "0x16f3daf20",
          "symbol_address": "0x100da0d08",
          "column": 40,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::do_call::hbfefa096cde588e7",
          "line": 552
        },
        {
          "ip": "0x100da0d08",
          "sp": "0x16f3daf20",
          "symbol_address": "0x100da0d08",
          "column": 19,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs",
          "function": "std::panicking::try::hebf8b6694f3819d7",
          "line": 516
        },
        {
          "ip": "0x100da0d08",
          "sp": "0x16f3daf20",
          "symbol_address": "0x100da0d08",
          "column": 14,
          "file": "/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs",
          "function": "std::panic::catch_unwind::h62e366e1b226d45f",
          "line": 146
        },
        {
          "ip": "0x100da0d08",
          "sp": "0x16f3daf20",
          "symbol_address": "0x100da0d08",
          "column": 30,
